server:
  port: 8309
spring:
  application:
    name: invoice-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecs_billing
    username: ecs
    password: ecs_secret
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata
  flyway:
    enabled: true
    table: invoice_flyway_history
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ecs
