server:
  port: 8094
spring:

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecs_platform
    username: ecs
    password: ecs_secret
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ecs

ecs:
  notify:
    gupshup:
      base-url: https://api.gupshup.io
      api-key: ${GUPSHUP_API_KEY:dev-key}
    msg91:
      base-url: https://api.msg91.com
      auth-key: ${MSG91_AUTH_KEY:dev-key}
