from pathlib import Path

root = Path(__file__).resolve().parents[2]

services = [
    ("api-gateway", "platform-infrastructure/api-gateway", 8080, None),
    ("search-solr-indexer", "platform-infrastructure/search-solr-indexer", 8090, None),
    ("pincode-master-service", "platform-infrastructure/pincode-master-service", 8091, "ecs_platform"),
    ("kafka-dlq-manager", "platform-infrastructure/kafka-dlq-manager", 8092, "ecs_platform"),
    ("mca-audit-trail-service", "platform-infrastructure/mca-audit-trail-service", 8093, "ecs_platform"),
    ("notification-service", "platform-infrastructure/notification-service", 8094, None),
    ("product-service", "master-enterprise-catalog/product-service", 8101, "ecs_mec"),
    ("variant-matrix-service", "master-enterprise-catalog/variant-matrix-service", 8102, None),
    ("serial-imei-tracking-service", "master-enterprise-catalog/serial-imei-tracking-service", 8103, None),
    ("b2b-tiered-catalog-service", "master-enterprise-catalog/b2b-tiered-catalog-service", 8104, None),
    ("component-bundle-service", "master-enterprise-catalog/component-bundle-service", 8105, None),
    ("cpq-rule-engine", "master-enterprise-catalog/cpq-rule-engine", 8106, None),
    ("dynamic-schema-engine", "master-enterprise-catalog/dynamic-schema-engine", 8107, None),
    ("offer-promotion-service", "master-enterprise-catalog/offer-promotion-service", 8108, None),
    ("temporal-activation-service", "master-enterprise-catalog/temporal-activation-service", 8109, None),
    ("media-dam-service", "master-enterprise-catalog/media-dam-service", 8110, None),
    ("bulk-catalog-import-service", "master-enterprise-catalog/bulk-catalog-import-service", 8111, None),
    ("catalog-sync-publisher", "master-enterprise-catalog/catalog-sync-publisher", 8112, None),
    ("cart-service", "order-management-system/cart-service", 8201, None),
    ("checkout-service", "order-management-system/checkout-service", 8202, None),
    ("order-orchestrator", "order-management-system/order-orchestrator", 8203, None),
    ("dynamic-price-engine", "order-management-system/dynamic-price-engine", 8204, None),
    ("atp-inventory-service", "order-management-system/atp-inventory-service", 8205, None),
    ("wms-fulfillment-service", "order-management-system/wms-fulfillment-service", 8206, None),
    ("ondc-seller-gateway", "order-management-system/ondc-seller-gateway", 8207, None),
    ("carrier-logistics-service", "order-management-system/carrier-logistics-service", 8208, None),
    ("bopis-pickup-service", "order-management-system/bopis-pickup-service", 8209, None),
    ("ndr-returns-rma-service", "order-management-system/ndr-returns-rma-service", 8210, None),
    ("catalog-consumer-service", "order-management-system/catalog-consumer-service", 8211, None),
    ("gst-tax-engine", "billing-system/gst-tax-engine", 8301, None),
    ("tcs-tds-compliance-engine", "billing-system/tcs-tds-compliance-engine", 8302, None),
    ("price-book-service", "billing-system/price-book-service", 8303, None),
    ("subscription-emi-service", "billing-system/subscription-emi-service", 8304, None),
    ("payment-gateway-service", "billing-system/payment-gateway-service", 8305, None),
    ("payment-gateway-plugins", "billing-system/payment-gateway-plugins", 8306, None),
    ("cod-remittance-reconcile-service", "billing-system/cod-remittance-reconcile-service", 8307, None),
    ("webhook-reconciliation-service", "billing-system/webhook-reconciliation-service", 8308, None),
    ("invoice-service", "billing-system/invoice-service", 8309, None),
    ("general-ledger-service", "billing-system/general-ledger-service", 8310, None),
    ("dunning-service", "billing-system/dunning-service", 8311, None),
    ("customer-360-service", "customer-relationship-management/customer-360-service", 8401, None),
    ("assisted-sales-service", "customer-relationship-management/assisted-sales-service", 8402, None),
    ("account-hierarchy-service", "customer-relationship-management/account-hierarchy-service", 8403, None),
    ("contact-address-service", "customer-relationship-management/contact-address-service", 8404, None),
    ("support-ticket-service", "customer-relationship-management/support-ticket-service", 8405, None),
    ("loyalty-rewards-service", "customer-relationship-management/loyalty-rewards-service", 8406, None),
    ("cart-abandonment-service", "customer-relationship-management/cart-abandonment-service", 8407, None),
    ("dpdp-compliance-service", "customer-relationship-management/dpdp-compliance-service", 8408, None),
]

gw_env = {
    "ECS_URI_SEARCH": "http://search-solr-indexer:8090",
    "ECS_URI_PINCODE": "http://pincode-master-service:8091",
    "ECS_URI_CART_ABANDON": "http://cart-abandonment-service:8407",
    "ECS_URI_WEBHOOKS": "http://webhook-reconciliation-service:8308",
    "ECS_URI_PRODUCTS": "http://product-service:8101",
    "ECS_URI_VARIANTS": "http://variant-matrix-service:8102",
    "ECS_URI_IMEI": "http://serial-imei-tracking-service:8103",
    "ECS_URI_B2B": "http://b2b-tiered-catalog-service:8104",
    "ECS_URI_BUNDLES": "http://component-bundle-service:8105",
    "ECS_URI_CPQ": "http://cpq-rule-engine:8106",
    "ECS_URI_SCHEMA": "http://dynamic-schema-engine:8107",
    "ECS_URI_OFFERS": "http://offer-promotion-service:8108",
    "ECS_URI_TEMPORAL": "http://temporal-activation-service:8109",
    "ECS_URI_DAM": "http://media-dam-service:8110",
    "ECS_URI_IMPORT": "http://bulk-catalog-import-service:8111",
    "ECS_URI_CART": "http://cart-service:8201",
    "ECS_URI_CHECKOUT": "http://checkout-service:8202",
    "ECS_URI_ORDERS": "http://order-orchestrator:8203",
    "ECS_URI_PRICES": "http://dynamic-price-engine:8204",
    "ECS_URI_ATP": "http://atp-inventory-service:8205",
    "ECS_URI_WMS": "http://wms-fulfillment-service:8206",
    "ECS_URI_ONDC": "http://ondc-seller-gateway:8207",
    "ECS_URI_CARRIER": "http://carrier-logistics-service:8208",
    "ECS_URI_BOPIS": "http://bopis-pickup-service:8209",
    "ECS_URI_NDR": "http://ndr-returns-rma-service:8210",
    "ECS_URI_GST": "http://gst-tax-engine:8301",
    "ECS_URI_TCS": "http://tcs-tds-compliance-engine:8302",
    "ECS_URI_PRICEBOOK": "http://price-book-service:8303",
    "ECS_URI_EMI": "http://subscription-emi-service:8304",
    "ECS_URI_PAY": "http://payment-gateway-service:8305",
    "ECS_URI_COD": "http://cod-remittance-reconcile-service:8307",
    "ECS_URI_INVOICE": "http://invoice-service:8309",
    "ECS_URI_LEDGER": "http://general-ledger-service:8310",
    "ECS_URI_DUNNING": "http://dunning-service:8311",
    "ECS_URI_CUSTOMERS": "http://customer-360-service:8401",
    "ECS_URI_ASSISTED": "http://assisted-sales-service:8402",
    "ECS_URI_ACCOUNTS": "http://account-hierarchy-service:8403",
    "ECS_URI_ADDRESSES": "http://contact-address-service:8404",
    "ECS_URI_TICKETS": "http://support-ticket-service:8405",
    "ECS_URI_LOYALTY": "http://loyalty-rewards-service:8406",
    "ECS_URI_DPDP": "http://dpdp-compliance-service:8408",
    "ECS_URI_DLQ": "http://kafka-dlq-manager:8092",
    "ECS_URI_AUDIT": "http://mca-audit-trail-service:8093",
    "ECS_URI_NOTIFY": "http://notification-service:8094",
    "SPRING_DATA_REDIS_HOST": "redis",
    "SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI": "http://keycloak:8080/realms/ecs",
}

lines = [
    "# Full microservice stack. Package JARs first: mvn -DskipTests package",
    "# docker compose -f docker-compose.infra.yml -f docker-compose.apps.yml up -d --build",
    "",
    "name: ecs",
    "",
    "networks:",
    "  ecs:",
    "    name: ecs-net",
    "",
    "x-jvm-env: &jvm-env",
    '  SPRING_THREADS_VIRTUAL_ENABLED: "true"',
    "  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:19092",
    "  SPRING_DATA_REDIS_HOST: redis",
    "  SPRING_DATASOURCE_USERNAME: ecs",
    "  SPRING_DATASOURCE_PASSWORD: ecs_secret",
    '  ECS_SECURITY_ENABLED: "false"',
    "  ECS_SOLR_BASE_URL: http://solr:8983/solr",
    "",
    "x-depends: &depends",
    "  postgres:",
    "    condition: service_healthy",
    "  redis:",
    "    condition: service_healthy",
    "  kafka:",
    "    condition: service_started",
    "",
    "services:",
]

for name, path, port, db in services:
    jar = f"{path}/target/{name}-1.0.0-SNAPSHOT.jar"
    lines += [
        f"  {name}:",
        "    build:",
        "      context: .",
        "      dockerfile: ops/docker/Dockerfile.jvm",
        "      args:",
        f"        JAR_FILE: {jar}",
        f"    image: ecs/{name}:1.0.0-SNAPSHOT",
        f'    ports: ["{port}:{port}"]',
        "    environment:",
        "      <<: *jvm-env",
        f'      SERVER_PORT: "{port}"',
    ]
    if db:
        lines.append(f"      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/{db}")
    if name == "api-gateway":
        for key, value in gw_env.items():
            lines.append(f"      {key}: {value}")
    lines += [
        "    depends_on:",
        "      <<: *depends",
        "    healthcheck:",
        f'      test: ["CMD", "curl", "-sf", "http://localhost:{port}/actuator/health"]',
        "      interval: 20s",
        "      timeout: 5s",
        "      retries: 10",
        "      start_period: 40s",
        "    networks: [ecs]",
        "",
    ]

for app, port in [
    ("ecommerce-storefront-portal", 5173),
    ("master-admin-portal", 5174),
    ("catalog-admin-studio", 5175),
    ("order-admin-portal", 5176),
    ("billing-admin-portal", 5177),
    ("crm-admin-portal", 5178),
]:
    lines += [
        f"  {app}:",
        "    build:",
        "      context: .",
        "      dockerfile: ops/docker/Dockerfile.web",
        "      args:",
        f"        APP_NAME: {app}",
        f'    ports: ["{port}:80"]',
        "    depends_on:",
        "      api-gateway:",
        "        condition: service_started",
        "    networks: [ecs]",
        "",
    ]

out = root / "docker-compose.apps.yml"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out}")
